--DROP SCHEMA public CASCADE;
--CREATE SCHEMA public;

CREATE TYPE "user_role" AS ENUM (
  'user',
  'admin'
);

CREATE TYPE "booking_status" AS ENUM (
  'confirmed',
  'cancelled',
  'completed'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "full_name" VARCHAR(255) NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "balance" BIGINT DEFAULT 0,
  "phone_number" VARCHAR(20) not null,
  "address" VARCHAR(255) NOT NULL,
  "role" user_role DEFAULT 'user',
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "vehicles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "quantity" INT DEFAULT 1,
  "daily_rate" BIGINT NOT NULL,
  "category" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "bookings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "vehicle_id" INT NOT NULL,
  "booking_start" TIMESTAMP NOT NULL,
  "booking_end" TIMESTAMP NOT NULL,
  "total_price" BIGINT NOT NULL,
  "status" booking_status DEFAULT 'confirmed',
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  CONSTRAINT "valid_booking_dates" CHECK (booking_end > booking_start)
);

ALTER TABLE "bookings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookings" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;


select * from bookings;